// Bundles the overlay into one paste-able file: dist/orb-overlay.js
//
//   node build.js
//
// One file because of how it gets deployed: pasted into the Run Script widget
// on trader.liquidcharts.com, or into the browser console. There is no module
// loader on the other side and no server to fetch from, so `require` has to be
// gone by the time the code ships. Each source file already ends by publishing
// itself onto `globalThis`, and the wrapper below defines a `require` shim that
// resolves to those, so the same sources run unmodified under `node --test`.
//
// No minification on purpose. This is a script somebody is about to paste into
// a page that can place real orders; being able to read it first is worth more
// than the bytes.

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const ORDER = ['clock.js', 'strategy.js', 'adapter.js', 'bot.js', 'panel.js', 'main.js'];
const OUT = path.join(ROOT, 'dist', 'orb-overlay.js');

const GLOBALS = {
  './clock.js': 'OrbClock',
  './strategy.js': 'OrbStrategy',
  './adapter.js': 'OrbAdapter',
  './bot.js': 'OrbBot',
  './panel.js': 'OrbPanel',
};

function header() {
  const stamp = new Date().toISOString().slice(0, 19).replace('T', ' ');
  return `// ORB Autobot -- opening range breakout overlay
// Built ${stamp} UTC from web/qt-orb/src by build.js. Do not edit this file;
// edit the sources and rebuild, or the next build will overwrite your changes.
//
// Paste into the Run Script widget on your charting platform, or into the
// browser console on the trading page. It starts in DRY RUN: it decides and
// reports and sends nothing until you untick that box.
//
// Requires a platform adapter. See adapter.js: eight calls stand between this
// and a live account, and they are left unwired rather than guessed.
`;
}

function build() {
  const parts = [header(), '(function () {\n\'use strict\';\n'];

  // The shim: `require('./clock.js')` becomes a lookup of the global that
  // clock.js published a moment earlier. Anything unexpected throws loudly
  // rather than returning undefined and failing three calls later.
  parts.push(`var __mods = {};
function require(name) {
  var map = ${JSON.stringify(GLOBALS)};
  var key = map[name];
  if (!key || !__mods[key]) throw new Error('bundle error: cannot resolve ' + name);
  return __mods[key];
}
var globalThis_ = (typeof globalThis !== 'undefined') ? globalThis : window;
`);

  for (const file of ORDER) {
    const full = path.join(ROOT, 'src', file);
    if (!fs.existsSync(full)) throw new Error(`missing source: src/${file}`);
    let code = fs.readFileSync(full, 'utf8');
    // Each source ends with a CommonJS export and a globalThis publish. Inside
    // the bundle the CommonJS half is meaningless, so it is stripped and the
    // publish is redirected into the shim's registry.
    code = code.replace(/if \(typeof module !== 'undefined' && module\.exports\)[^\n]*\n/g, '');
    code = code.replace(
      /if \(typeof globalThis !== 'undefined'\) globalThis\.(\w+) = api;/g,
      '__mods[\'$1\'] = api; globalThis_.$1 = api;');
    // The `const x = (typeof require !== 'undefined') ? require(...)` preambles
    // work as-is against the shim, so they are left alone deliberately.
    //
    // Each module gets its own function scope. Concatenating them into one
    // shared scope collides immediately: every source declares `const api` at
    // the end, and a duplicate `const` is a SyntaxError that takes the whole
    // bundle down at paste time rather than at build time.
    parts.push(`\n// ===== src/${file} ${'='.repeat(Math.max(0, 58 - file.length))}\n`);
    parts.push('(function () {\n');
    parts.push(code);
    parts.push('\n})();\n');
  }

  parts.push('\n})();\n');
  const bundle = parts.join('');

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, bundle, 'utf8');

  // A bundle that still contains a bare `module.exports` would throw the moment
  // it is pasted, and the browser's error would point at a line number in a
  // file nobody has. Cheaper to catch here.
  if (/module\.exports/.test(bundle)) {
    throw new Error('build produced a bundle still containing module.exports');
  }
  const kb = (Buffer.byteLength(bundle) / 1024).toFixed(1);
  console.log(`wrote ${path.relative(ROOT, OUT)}  (${kb} kB, ${bundle.split('\n').length} lines)`);
  return OUT;
}

if (require.main === module) build();
module.exports = { build, OUT, ORDER };
